# Generated by Django 4.1.7 on 2023-03-08 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_product_product_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_user',
            new_name='user_name',
        ),
    ]
