# Generated by Django 4.1.7 on 2023-03-08 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_product_user_product_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user_name',
            new_name='product_user',
        ),
    ]
