# Generated by Django 4.1.7 on 2023-03-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='company_name',
            field=models.CharField(max_length=150),
        ),
    ]
